# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f5f326db5470d0b68c0fecb5ed7c75de2a51139a75cfa159dfece01aa31f3897df0ae4a1012b478021c0b5713fcf5e24d003fa2ff5a6e4fd7f55a642a88fa48

test:
  secret_key_base: 9b920fd05c8b18c0932b03a2d82506b1c86ca425c622703d3ccaacd272b96659bee43aef1d739b5355d00defb6b93e50b68fcaea844e8ab4eefd871ee617f605

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
